#!/usr/bin/env bash
CUDA_VISIBLE_DEVICES=1 python3 main_slomo_skrcjstk_15frame_tf2.py \
    --output_dir ./train_slomo_skrcjstk_15frame_tf2_OF2_trainable_itp_layer_n_8_w_grad_loss/ \
    --summary_dir ./train_slomo_skrcjstk_15frame_tf2_OF2_trainable_itp_layer_n_8_w_grad_loss/log/ \
    --mode train \
    --batch_size 8 \
    --learning_rate 0.0001 \
    --decay_step 60000 \
    --decay_rate 0.1 \
    --stair True \
    --beta 0.9 \
    --trainingSetStart 1000 \
    --trainingSetLimit 1300  \
    --testSetStart 1000 \
    --testSetLimit 1010 \
    --frameLimit 141 \
    --max_iter 25000 \
    --start_step 0 \
    --test_step 25000 \
    --over_lap 0 \
    --save_uni 0 \
    --save_uni_dir /media/cgnadeep2/hdd2/sharedfolder/skrcjstk_data/manta_data/data_skrcjstk7/train2D_3frame_full_split/ \